import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./joygo-supabase-config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY),$=id=>document.getElementById(id);let profiles=[];
const escapeHtml=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const say=(t,error=false)=>{$("message").textContent=t;$('message').classList.toggle('error',error)};
const labelRole=r=>({admin:"管理員",member:"正式會員",trial:"試用會員"}[r]||r),labelStatus=s=>s==='active'?'啟用':'停用';
function stats(){ $("total").textContent=profiles.length;$("members").textContent=profiles.filter(x=>x.role==='member').length;$("trials").textContent=profiles.filter(x=>x.role==='trial').length;$("suspended").textContent=profiles.filter(x=>x.status==='suspended').length }
function render(){const q=$("search").value.trim().toLowerCase(),items=profiles.filter(p=>`${p.display_name} ${p.email}`.toLowerCase().includes(q));$("rows").innerHTML=items.length?items.map(p=>`<tr data-id="${p.id}"><td><b>${escapeHtml(p.display_name)}</b><br><small>${escapeHtml(p.email)}</small></td><td><select data-field="role"><option value="trial" ${p.role==='trial'?'selected':''}>試用會員</option><option value="member" ${p.role==='member'?'selected':''}>正式會員</option><option value="admin" ${p.role==='admin'?'selected':''}>管理員</option></select></td><td><select data-field="status"><option value="active" ${p.status==='active'?'selected':''}>啟用</option><option value="suspended" ${p.status==='suspended'?'selected':''}>停用</option></select></td><td><input data-field="expires_at" type="date" value="${p.expires_at?String(p.expires_at).slice(0,10):''}" ${p.role==='admin'?'disabled':''}></td><td><button class="save" data-save>儲存</button></td></tr>`).join(''):`<tr><td colspan="5" class="empty">沒有符合的會員</td></tr>`}
async function load(){say('載入會員名單…');const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='joygo-auth.html';return}const {data:self,error:selfError}=await supabase.from('profiles').select('role,status').eq('id',user.id).single();if(selfError||self?.role!=='admin'||self?.status!=='active'){say('您沒有管理員權限。',true);$("rows").innerHTML='<tr><td colspan="5" class="empty danger">僅管理員可查看會員名單</td></tr>';return}const {data,error}=await supabase.from('profiles').select('*').order('created_at',{ascending:false});if(error){say(`讀取失敗：${error.message}`,true);return}profiles=data||[];stats();render();say(`已載入 ${profiles.length} 位會員`)}
$("rows").addEventListener('click',async e=>{const button=e.target.closest('[data-save]');if(!button)return;const tr=button.closest('tr'),id=tr.dataset.id,role=tr.querySelector('[data-field=role]').value,status=tr.querySelector('[data-field=status]').value,date=tr.querySelector('[data-field=expires_at]').value;button.disabled=true;say('正在儲存…');const update={role,status,expires_at:role==='admin'||!date?null:new Date(`${date}T23:59:59`).toISOString(),updated_at:new Date().toISOString()};const {error}=await supabase.from('profiles').update(update).eq('id',id);button.disabled=false;if(error){say(`儲存失敗：${error.message}`,true);return}say('會員資料已更新。');await load()});
$("search").addEventListener('input',render);$("refresh").addEventListener('click',load);load();
